[package]
name = "procmacroplay"
version = "0.1.0"
authors = ["zancas <zancas@zingolabs.com>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "*"
